### ISSUE TITLE
Throwing exception on missing CC fields for free subscription

### ISSUE THREAD

**Issue by ejrudy** [marcguyer/cheddargetter-client-php#11]
Hello-

I'm trying to create a customer with a free subscription during signup to my app. The following is the procedure for the signup:

```php
$data = array(
	        'code'		=> $thisUser->GetEmail( ),
	        'firstName'	=> $thisUser->GetFirstName( ),
	        'lastName'	=> $thisUser->GetLastName( ),
	        'email'		=> $thisUser->GetEmail( ),
	        'subscription'	=> array(
	                'planCode'  	=> 'Sendgarden'
	        )
);

try {
    $thisCustomer = $client->newCustomer($data);
    $thisCustomer->handleEmbeddedErrors();
    $thisCustomerArray	= $thisCustomer->toArray( );
} catch (CheddarGetter_Response_Exception $re) {
    die($re->getCode() . '-' . $re->getAuxCode() . ': ' . $re->getMessage());
}
```

This is throwing a `412-subscription[ccFirstName]:isEmpty: A value is required` even though the docs say that it should be able to create a user with a free subscription without those fields.

Also not entirely sure if this is an issue with the PHP lib or the API itself.

**Comment by marcguyer** [comment]
Hi @ejrudy -- The 412 response is returned by the CheddarGetter API which is converted into an exception in this client lib. I suggest [opening a support thread with the CheddarGetter team](http://support.cheddargetter.com/discussion/new) to seek a solution.

**Comment by ejrudy** [comment]
Thanks Marc-
