### ISSUE TITLE
How to implement cheddargetter with laravel 5

### ISSUE THREAD

**Issue by payalchauhan71** [marcguyer/cheddargetter-client-php#9]

**Comment by marcguyer** [comment]
Hi @payalchauhan71 -- This lib is a generic wrapper. It isn't tied to any particular framework so you can write something to work it in with your laravel app. I'm not aware of any laravel forks for this particular repo but there might be 1 or 2 in the wild. Maybe @jsiebach has some suggestions...

**Comment by jsiebach** [comment]
@payalchauhan71 @marcguyer I haven't made a package before, but I took a quick shot.  This lets you inject a CheddarGetter_Client into any controller, and it will automatically set the url, username, and password for you:

https://github.com/jsiebach/laravel-cheddar

Would love some feedback!  If people end up using it I could look at increasing the functionality...

**Comment by payalchauhan71** [comment]
@jsiebach Thanks for help! it's work for me.
i have one proble wanting to test out the PHP API, preferably on localhost. Is it possible to do this without purchasing an SSL certificate?
i got an error like:
cUrl session resulted in an error: (60)SSL certificate problem: self signed certificate in certificate chain

**Comment by jsiebach** [comment]
I'm not familiar with the cheddargetter api much so I will let someone else take that one. Glad the Service Provider worked for you!

**Comment by marcguyer** [comment]
@payalchauhan71 you can run your dev environment on localhost but you'll need to connect to cheddargetter.com to talk to the API.
